### ISSUE TITLE
Playing the MAX_PATH crazyiness

### ISSUE THREAD

**Issue by russau** [pythianarora/proj-aws-dev-tools#2]
I've hit some problems building like this because of windows MAX_PATH limitations - i.e. https://github.com/Microsoft/msbuild/issues/53

Putting this here with the hopes that it fixes a problem for someone else.  I get the error:

```
error MSB4102: The value "C:\codebuild\tmp\src603193139\src\git-codecommit.us-east-1.amazonaws.com\v1\repos\...\packages\MSBuild.Microsoft.VisualStudio.Web.targets.14.0.0.3\tools\VSToolsPath\Web\\Microsoft.Web.Publishing\ImportAfter\Microsoft.Web.AzureAD.Publishing.targets" of the "Project" attribute in element <Import> is invalid. 
```

The low tech fix was to copy the source to a shorter folder name, building it there, and copying it back.

``` yaml
env:
  variables:
    SOLUTION: c:\build\MarkdownMachine.sln
    SHORT_DIRECTORY: c:\build\
    PACKAGE_DIRECTORY: c:\build\packages\
    DOTNET_FRAMEWORK: 4.6.2

phases:
  build:
    commands:
      - 'Copy-Item \\?\c:$env:CODEBUILD_SRC_DIR -Destination $env:SHORT_DIRECTORY -Recurse -Force'
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -Verbosity detailed -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
      - 'Copy-Item $env:SHORT_DIRECTORY\* -Destination \\?\c:$env:CODEBUILD_SRC_DIR -Recurse -Force'
```
